const productList = [{
		"area": 264.60,
		"averagePrice": null,
		"buildArea": 61.20,
		"city": "聊城",
		"competingId": "277363商业",
		"competingProductName": "九州国际",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "东昌府区",
		"firstOpeningDate": null,
		"fullName": "山东省聊城东昌府区",
		"mainProductArea": "120-140",
		"mainProducts": "商业",
		"mainhouse": "2居/3居",
		"maxArea": "141",
		"minArea": "82",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.60,
		"province": "山东省",
		"town": ""
	},
	{
		"area": 264.60,
		"averagePrice": null,
		"buildArea": 61.20,
		"city": "聊城",
		"competingId": "277363洋房",
		"competingProductName": "（清盘）裕昌九州国际",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "东昌府区",
		"firstOpeningDate": null,
		"fullName": "山东省聊城东昌府区",
		"mainProductArea": "120-140",
		"mainProducts": "洋房",
		"mainhouse": "2居/3居",
		"maxArea": "141",
		"minArea": "82",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.60,
		"province": "山东省",
		"town": ""
	},
	{
		"area": 264.60,
		"averagePrice": null,
		"buildArea": 61.20,
		"city": "聊城",
		"competingId": "277363车位",
		"competingProductName": "（清盘）裕昌九州国际",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "东昌府区",
		"firstOpeningDate": null,
		"fullName": "山东省聊城东昌府区",
		"mainProductArea": "120-140",
		"mainProducts": "车位",
		"mainhouse": "2居/3居",
		"maxArea": "141",
		"minArea": "82",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.60,
		"province": "山东省",
		"town": ""
	},
	{
		"area": 162.00,
		"averagePrice": null,
		"buildArea": 27.86,
		"city": "濮阳",
		"competingId": "268214商业",
		"competingProductName": "龙鼎御园",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "台前县",
		"firstOpeningDate": null,
		"fullName": "河南省濮阳台前县",
		"mainProductArea": "135-215",
		"mainProducts": "商业",
		"mainhouse": "3居/4居/5居/6居",
		"maxArea": "215",
		"minArea": "135",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.58,
		"province": "河南省",
		"town": ""
	},
	{
		"area": 162.00,
		"averagePrice": null,
		"buildArea": 27.86,
		"city": "濮阳",
		"competingId": "268214洋房",
		"competingProductName": "龙鼎御园",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "台前县",
		"firstOpeningDate": null,
		"fullName": "河南省濮阳台前县",
		"mainProductArea": "135-215",
		"mainProducts": "洋房",
		"mainhouse": "3居/4居/5居/6居",
		"maxArea": "215",
		"minArea": "135",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.58,
		"province": "河南省",
		"town": ""
	},
	{
		"area": 162.00,
		"averagePrice": null,
		"buildArea": 27.86,
		"city": "濮阳",
		"competingId": "268214车位",
		"competingProductName": "龙鼎御园",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "台前县",
		"firstOpeningDate": null,
		"fullName": "河南省濮阳台前县",
		"mainProductArea": "135-215",
		"mainProducts": "车位",
		"mainhouse": "3居/4居/5居/6居",
		"maxArea": "215",
		"minArea": "135",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.58,
		"province": "河南省",
		"town": ""
	},
	{
		"area": 86.20,
		"averagePrice": null,
		"buildArea": 26.09,
		"city": "银川",
		"competingId": "38553商业",
		"competingProductName": "龙马阳光城",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "金凤区",
		"firstOpeningDate": null,
		"fullName": "宁夏回族自治区银川金凤区",
		"mainProductArea": "",
		"mainProducts": "商业",
		"mainhouse": "2居/3居",
		"maxArea": "138",
		"minArea": "92",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 3.55,
		"province": "宁夏回族自治区",
		"town": ""
	},
	{
		"area": 86.20,
		"averagePrice": null,
		"buildArea": 26.09,
		"city": "银川",
		"competingId": "38553洋房",
		"competingProductName": "龙马阳光城",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "金凤区",
		"firstOpeningDate": null,
		"fullName": "宁夏回族自治区银川金凤区",
		"mainProductArea": "",
		"mainProducts": "洋房",
		"mainhouse": "2居/3居",
		"maxArea": "138",
		"minArea": "92",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 3.55,
		"province": "宁夏回族自治区",
		"town": ""
	},
	{
		"area": 86.20,
		"averagePrice": null,
		"buildArea": 26.09,
		"city": "银川",
		"competingId": "38553车位",
		"competingProductName": "龙马阳光城",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "金凤区",
		"firstOpeningDate": null,
		"fullName": "宁夏回族自治区银川金凤区",
		"mainProductArea": "",
		"mainProducts": "车位",
		"mainhouse": "2居/3居",
		"maxArea": "138",
		"minArea": "92",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 3.55,
		"province": "宁夏回族自治区",
		"town": ""
	},
	{
		"area": 179.01,
		"averagePrice": null,
		"buildArea": 29.84,
		"city": "南通",
		"competingId": "129858商业",
		"competingProductName": "龙馨家园",
		"cumulativeDigestionRate": null,
		"cumulativeOutputQuantity": "",
		"decorate": "",
		"district": "启东市",
		"firstOpeningDate": null,
		"fullName": "江苏省南通启东市",
		"mainProductArea": "",
		"mainProducts": "商业",
		"mainhouse": "2居/3居",
		"maxArea": "132",
		"minArea": "97",
		"newestDigestionRate": null,
		"newestOpeningDate": null,
		"newestOutputQuantity": "",
		"potRatio": 2.50,
		"province": "江苏省",
		"town": ""
	}
]

export default {
	productList
}